#/data/fcrepo-home/config/fcrepo.properties

fcrepo.auth.enabled=false
#fcrepo.persistence.defaultDigestAlgorithm = sha512

fcrepo.db.url=jdbc:postgresql://${POSTGRES_HOST}:5432/fcrepo
fcrepo.db.user=${POSTGRES_USER}
fcrepo.db.password=${POSTGRES_PASSWORD}