FROM fcrepo/fcrepo:7.0.0-tomcat10

COPY configFiles/fedora/web.xml /usr/local/tomcat/webapps/fcrepo/WEB-INF/
COPY configFiles/fedora/fcrepo.properties /usr/local/tomcat/fcrepo-home/config/fcrepo.properties
#COPY configFiles/fedora/config.json /usr/local/tomcat/fcrepo-home/data/ocfl-root/extensions/0004-hashed-n-tuple-storage-layout/config2.json