FROM fcrepo/fcrepo:6.1.1

COPY configFiles/fedora/web.xml /usr/local/tomcat/webapps/fcrepo/WEB-INF/
#COPY configFiles/fedora/no-auth-web.xml /usr/local/tomcat/webapps/fcrepo/WEB-INF/
#COPY configFiles/tomcat/fcrepo.xml $CATALINA_HOME/conf/Catalina/localhost/